import { SCENE_UNIVERSE } from './kodexUniverse.js';

export const thresholdArtifactRecord = {
  archive: 'AR-117',
  specimen: 'SP-02',
  subject: SCENE_UNIVERSE.threshold.subject,
  node: SCENE_UNIVERSE.threshold.node,
  location: SCENE_UNIVERSE.threshold.location,
  protocol: SCENE_UNIVERSE.threshold.protocol,
  signal: SCENE_UNIVERSE.threshold.signal,
  status: 'PRESERVED',
  clearance: SCENE_UNIVERSE.threshold.clearance,
  threat: SCENE_UNIVERSE.threshold.threat,
  operator: SCENE_UNIVERSE.threshold.operator,
  checksum: '8F21-A90C',
  timestamp: '2026-07-29 // 23:17 UTC',
  title: 'DESCENT · Threshold Source',
  type: 'Archive work / portal source',
  origin: 'Original archive work + live portal shell',
  edition: 'Uneditioned source',
  provenance: 'Ocin / Wenu Mapu / KODEX−∞',
  license: 'All rights reserved',
  availability: 'Threshold source only',
  dossierHref: '/kodex/works/',
  collectHref: '/kodex/store/',
};

export const prologueObservationRecord = {
  archive: 'AR-118',
  specimen: 'SP-03',
  subject: SCENE_UNIVERSE.prologue.subject,
  node: SCENE_UNIVERSE.prologue.node,
  location: SCENE_UNIVERSE.prologue.location,
  protocol: SCENE_UNIVERSE.prologue.protocol,
  signal: SCENE_UNIVERSE.prologue.signal,
  status: 'OBSERVING',
  clearance: SCENE_UNIVERSE.prologue.clearance,
  threat: SCENE_UNIVERSE.prologue.threat,
  operator: SCENE_UNIVERSE.prologue.operator,
  checksum: 'B1C7-4D2E',
  timestamp: '2026-07-29 // 23:24 UTC',
  title: 'READ THE PROTOCOL',
  statement: 'This is not a gallery.',
  mantra: 'Every signal is a work. Read it. Generate from it. Carry it.',
  microLabel: 'Observation field · relational scan active',
  notes: [
    'The archive detects relation before identity.',
    'Observation changes the memory that returns to the visitor.',
    'Every signal can be read, generated from, and carried forward.',
    'Reduced motion preserves all meaning while the system remains aware.',
  ],
};
