import type { KodexTempleRecipe } from "./types";

export const signalTempleRecipe: KodexTempleRecipe = {
  id: "signal-temple-b",
  title: "SIGNAL TEMPLE",
  subtitle: "A chamber where architecture, signal and remembered traversal become one field.",
  nodeCoordinate: "B",
  organismPreset: "signal-vortex",
  organismFallback: "/img/kodex/organisms/signal-vortex-fallback.svg",
  organismLabel: "SIGNAL VORTEX · temple organism",
  organismDescription:
    "A procedural convergence field suspended above the central altar. The surrounding temple changes independently from the renderer.",
  palette: {
    void: "#030208",
    shadow: "#090511",
    structure: "#f0a63b",
    signal: "#7347ff",
    spectral: "#28d8ff",
    memory: "#ff4fbd",
    white: "#fff7ea",
  },
  architecture: {
    archLayers: 11,
    domeLayers: 9,
    candleCount: 72,
    memoryLights: 25,
  },
  stateProfiles: {
    DORMANT: {
      state: "DORMANT",
      description: "The chamber is mostly dark. The architecture is incomplete and the signal remains distant.",
      architectureEnergy: 0.24,
      candleEnergy: 0.34,
      spectralEnergy: 0.08,
      depth: 0.62,
      organismScale: 0.78,
      memoryVisibility: 0.08,
    },
    AWARE: {
      state: "AWARE",
      description: "The chamber recognizes presence. Rings, routes and structural light begin to align.",
      architectureEnergy: 0.46,
      candleEnergy: 0.56,
      spectralEnergy: 0.25,
      depth: 0.78,
      organismScale: 0.88,
      memoryVisibility: 0.28,
    },
    ACTIVE: {
      state: "ACTIVE",
      description: "The altar is active. Signal and architecture exchange state through the node runtime.",
      architectureEnergy: 0.7,
      candleEnergy: 0.82,
      spectralEnergy: 0.54,
      depth: 0.9,
      organismScale: 1,
      memoryVisibility: 0.52,
    },
    MUTATED: {
      state: "MUTATED",
      description: "A revisited chamber exposes a different geometry. Previous decisions are visible as structural mutation.",
      architectureEnergy: 0.88,
      candleEnergy: 0.7,
      spectralEnergy: 0.78,
      depth: 1,
      organismScale: 1.06,
      memoryVisibility: 0.88,
    },
    RESONANT: {
      state: "RESONANT",
      description: "Memory, signal and route are temporarily coherent. A second spatial layer becomes perceptible.",
      architectureEnergy: 1,
      candleEnergy: 1,
      spectralEnergy: 1,
      depth: 1.08,
      organismScale: 1.12,
      memoryVisibility: 1,
    },
  },
  actions: [
    {
      id: "OBSERVE",
      label: "OBSERVE",
      description: "Attend without changing the field.",
      nextState: "AWARE",
      emits: "kodex:temple-observe",
    },
    {
      id: "ISOLATE",
      label: "ISOLATE",
      description: "Reduce the visible field to a selected signal relation.",
      nextState: "ACTIVE",
      emits: "kodex:temple-isolate",
    },
    {
      id: "TRACE",
      label: "TRACE",
      description: "Expose route-memory relations across the chamber.",
      nextState: "MUTATED",
      emits: "kodex:temple-trace",
    },
    {
      id: "RESONATE",
      label: "RESONATE",
      description: "Preview the high-coherence temple state for internal QA.",
      nextState: "RESONANT",
      emits: "kodex:temple-resonate",
    },
    {
      id: "RELEASE",
      label: "RELEASE",
      description: "Return the chamber to its lowest-energy state.",
      nextState: "DORMANT",
      emits: "kodex:temple-release",
    },
  ],
  provenance: {
    visualStatus: "ORIGINAL_KODEX_TRANSLATION",
    culturalRule:
      "Use geometric recursion, density, color, symmetry and spatial rhythm as abstract architectural principles. Do not reproduce sacred figures, inscriptions or culture-specific ritual symbols without provenance and explicit review.",
    epistemicStatus: "EXPERIMENTAL",
  },
};
