export const SIGNAL_THRESHOLD_RECIPE = Object.freeze({
  id: 'KDXM-001',
  title: 'SIGNAL_THRESHOLD',
  scene: 'THRESHOLD',
  duration: 12,
  stateIn: 'LATENT',
  stateOut: 'OPEN',
  sourceIds: ['KDX-FILM-001'],
  referenceIds: [],
  provenanceStatus: 'KODEX_INTERNAL',
  rightsStatus: 'PROJECT_OWNED_RECIPE',
  status: 'PROTOTYPE_SPEC',
  beats: [
    {
      id: 'KDXM-001-B01',
      type: 'VOID',
      start: 0,
      end: 2,
      subject: 'field',
      stateIn: 'LATENT',
      stateOut: 'DORMANT',
      params: { amplitude: 0.04, frequency: 0.2, damping: 0.92 },
      input: 'none',
      audio: 'silent',
      renderer: 'DOM_CSS',
      fallback: 'static latent marker',
    },
    {
      id: 'KDXM-001-B02',
      type: 'SIGNAL',
      start: 2,
      end: 4.2,
      subject: 'signal-line',
      stateIn: 'DORMANT',
      stateOut: 'AWARE',
      params: { amplitude: 0.28, frequency: 0.8, damping: 0.86 },
      input: 'none',
      audio: 'low transient',
      renderer: 'DOM_SVG',
      fallback: 'visible signal line',
    },
    {
      id: 'KDXM-001-B03',
      type: 'FOCUS',
      start: 4.2,
      end: 6.2,
      subject: 'portal-core',
      stateIn: 'AWARE',
      stateOut: 'OBSERVING',
      params: { amplitude: 0.18, frequency: 0.55, damping: 0.88 },
      input: 'pointer proximity optional',
      audio: 'sustained tone optional',
      renderer: 'DOM_CSS',
      fallback: 'centered focus marker',
    },
    {
      id: 'KDXM-001-B04',
      type: 'LOCK',
      start: 6.2,
      end: 8.4,
      subject: 'portal-rings',
      stateIn: 'OBSERVING',
      stateOut: 'LOCKED',
      params: { amplitude: 0.12, frequency: 0.4, damping: 0.94 },
      input: 'none',
      audio: 'lock click optional',
      renderer: 'DOM_CSS',
      fallback: 'aligned rings',
    },
    {
      id: 'KDXM-001-B05',
      type: 'OPEN',
      start: 8.4,
      end: 11,
      subject: 'aperture',
      stateIn: 'LOCKED',
      stateOut: 'OPEN',
      params: { amplitude: 0.34, frequency: 0.32, damping: 0.82 },
      input: 'none',
      audio: 'low release optional',
      renderer: 'DOM_CSS',
      fallback: 'open aperture',
    },
    {
      id: 'KDXM-001-B06',
      type: 'RETURN',
      start: 11,
      end: 12,
      subject: 'memory-trace',
      stateIn: 'OPEN',
      stateOut: 'OPEN',
      params: { amplitude: 0.08, frequency: 0.18, damping: 0.97 },
      input: 'none',
      audio: 'tail optional',
      renderer: 'DOM_CSS',
      fallback: 'residual trace',
    },
  ],
});
