import { holocoreOrbitalScene } from "../ascii/scenes/holocore-orbital.js";
import { holocoreSignalCoreScene } from "../ascii/scenes/holocore-signal-core.js";
import { holocoreInterferencePortalScene } from "../ascii/scenes/holocore-interference-portal.js";
import { holocoreToroidalFieldScene } from "../ascii/scenes/holocore-toroidal-field.js";
import {
  holocoreSignalVortexScene,
  holocoreDnaAscentScene,
  holocoreMemoryTreeScene,
  holocoreSkullArchiveScene,
  holocoreCosmologyOrbitScene,
  holocoreFieldOfEyesScene,
  holocoreHeartChamberScene,
  holocoreSourceChamberScene,
  holocoreReturnGateScene,
  holocoreLivingOrganismScene,
  holocoreSignalSeedScene,
} from "../ascii/scenes/holocore-core-family.js";

const spec = ({
  id,
  title,
  render,
  scene,
  accent,
  palette,
  label,
  provenance,
  sourceRefs = [],
  sourceStatus = "REFERENCE",
  archetype,
  topology,
  epistemic = "ART / COMP / SPEC",
}) => Object.freeze({
  id,
  title,
  render,
  scene,
  accent,
  palette: Object.freeze(palette),
  label,
  provenance,
  sourceRefs: Object.freeze(sourceRefs),
  sourceStatus,
  archetype,
  topology,
  epistemic,
});

const SPECIMENS = Object.freeze({
  "orbital-city": spec({
    id: "orbital-city",
    title: "ORBITAL CITY",
    render: "PROCEDURAL ASCII",
    scene: holocoreOrbitalScene,
    accent: "#a06cff",
    palette: ["#030208", "#151024", "#33204e", "#613b89", "#a06cff", "#eee7ff"],
    label: "Procedural ASCII holographic visualization of an exploded orbital city resolving inside a bounded KODEX viewport",
    provenance: "KODEX_SYNTHETIC_SPECULATIVE",
    sourceRefs: ["KDX-ROOT-RAW-009"],
    sourceStatus: "ANALYZED / MACHINE_REFERENCE",
    archetype: "AXIAL_EXPLODED",
    topology: "stacked-orbital-strata",
  }),
  "signal-core": spec({
    id: "signal-core",
    title: "SIGNAL CORE",
    render: "ASCII COHERENCE FIELD",
    scene: holocoreSignalCoreScene,
    accent: "#b7ff4a",
    palette: ["#020503", "#0b1c0b", "#17431d", "#3d7d31", "#9bd94c", "#f3ffe7"],
    label: "Synthetic KODEX signal core with luminous center, radial cage, data dither and bounded circulating signal packets",
    provenance: "KODEX_SYNTHETIC_REFERENCE_ABSTRACTION",
    sourceRefs: ["KDX-ROOT-RAW-009"],
    sourceStatus: "ANALYZED / MACHINE_REFERENCE",
    archetype: "RADIAL_CORE",
    topology: "contained-reactor-field",
  }),
  "interference-portal": spec({
    id: "interference-portal",
    title: "INTERFERENCE PORTAL",
    render: "ASCII PHASE FIELD",
    scene: holocoreInterferencePortalScene,
    accent: "#64d7ff",
    palette: ["#020408", "#081a26", "#123b50", "#286b83", "#68cce5", "#effcff"],
    label: "Synthetic KODEX optical phase field with slow interference, sixfold symmetry and a bounded central aperture",
    provenance: "KODEX_SYNTHETIC_REFERENCE_ABSTRACTION",
    sourceRefs: ["KDX-SYSTEM-PORTAL-RING-002"],
    sourceStatus: "CANON_CANDIDATE",
    archetype: "PORTAL_FIELD",
    topology: "radial-interference-aperture",
  }),
  "signal-vortex": spec({
    id: "signal-vortex",
    title: "SIGNAL VORTEX",
    render: "ASCII CONVERGENCE FIELD",
    scene: holocoreSignalVortexScene,
    accent: "#b47cff",
    palette: ["#020205", "#140b22", "#32204d", "#663c8e", "#b47cff", "#f4ecff"],
    label: "KODEX signal vortex translating radial noise into a bounded convergent pattern field",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-SCREEN-SIGNAL-014"],
    sourceStatus: "SCREEN_CANDIDATE",
    archetype: "RADIAL_VORTEX",
    topology: "centripetal-spiral-field",
  }),
  "dna-ascent": spec({
    id: "dna-ascent",
    title: "DNA ASCENT",
    render: "ASCII HELICAL AXIS",
    scene: holocoreDnaAscentScene,
    accent: "#d9b8ff",
    palette: ["#030208", "#17101f", "#38224b", "#765097", "#d9b8ff", "#fff7df"],
    label: "Double-helix KODEX field for DNA structure and symbolic lineage layers, kept epistemically separate",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ASTRAL-GATE-03", "KDX-ROOT-RAW-006"],
    sourceStatus: "CANON + TECHNICAL_REFERENCE",
    archetype: "AXIAL_HELIX",
    topology: "dual-strand-ascent",
    epistemic: "BIO / ART / SYM",
  }),
  "memory-tree": spec({
    id: "memory-tree",
    title: "MEMORY TREE",
    render: "ASCII BRANCHING GRAPH",
    scene: holocoreMemoryTreeScene,
    accent: "#d29b55",
    palette: ["#050301", "#181008", "#3b2812", "#795229", "#d29b55", "#fff0ce"],
    label: "KODEX archive tree with branching memory nodes, mirrored roots and recursive archive ring",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-SCREEN-ARCHIVE-015", "KDX-BANK-RAW-005"],
    sourceStatus: "SCREEN_CANDIDATE / ANALYZED",
    archetype: "BRANCHING_MEMORY",
    topology: "tree-root-graph",
    epistemic: "COMP / PHI / ART / SYM",
  }),
  "skull-archive": spec({
    id: "skull-archive",
    title: "SKULL ARCHIVE",
    render: "ASCII RELIC SCAN",
    scene: holocoreSkullArchiveScene,
    accent: "#f0a044",
    palette: ["#060302", "#211007", "#4a2410", "#95501f", "#f0a044", "#fff1d7"],
    label: "KODEX skull dossier separating morphology, evidence and symbolic interpretation within a bounded scan field",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ROOT-RAW-029"],
    sourceStatus: "ANALYZED",
    archetype: "FORENSIC_OBJECT",
    topology: "frontal-scan-reticle",
    epistemic: "BIO / ART / SPEC",
  }),
  "cosmology-orbit": spec({
    id: "cosmology-orbit",
    title: "COSMOLOGY ORBIT",
    render: "ASCII ORBIT MAP",
    scene: holocoreCosmologyOrbitScene,
    accent: "#ffcf70",
    palette: ["#050402", "#1d1609", "#4a3512", "#8e6728", "#ffcf70", "#fff5d6"],
    label: "KODEX orbital navigation field with concentric paths, moving nodes and a central source anchor",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-SYS-COSMO-ORBIT-001", "KDX-SCREEN-COSMOLOGY-012"],
    sourceStatus: "CANON_SYSTEM / SCREEN_CANDIDATE",
    archetype: "ORBITAL_MAP",
    topology: "concentric-node-system",
    epistemic: "PHY / COMP / ART / SPEC",
  }),
  "field-of-eyes": spec({
    id: "field-of-eyes",
    title: "FIELD OF EYES",
    render: "ASCII OBSERVER NETWORK",
    scene: holocoreFieldOfEyesScene,
    accent: "#a78cff",
    palette: ["#020206", "#131026", "#2f2852", "#5b4f91", "#a78cff", "#f4efff"],
    label: "Pointer-reactive KODEX observer network built from eye nodes without biometric inference or webcam input",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ASTRAL-GATE-02", "KDX-ASTRAL-006"],
    sourceStatus: "CANON / CANON_CANDIDATE",
    archetype: "DISTRIBUTED_OBSERVER",
    topology: "radial-gaze-network",
    epistemic: "ART / PHI / SYM / COMP",
  }),
  "heart-chamber": spec({
    id: "heart-chamber",
    title: "HEART CHAMBER",
    render: "ASCII PULSE FIELD",
    scene: holocoreHeartChamberScene,
    accent: "#d76652",
    palette: ["#060201", "#210806", "#4b1712", "#873428", "#d76652", "#ffe6d8"],
    label: "KODEX Heart Chamber with an anatomical motif, simulated pulse field and no fabricated biometric telemetry",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ASTRAL-GATE-05"],
    sourceStatus: "CANON",
    archetype: "PULSING_ORGAN",
    topology: "central-organ-concentric-field",
    epistemic: "BIO / ART / PHI / SYM",
  }),
  "source-chamber": spec({
    id: "source-chamber",
    title: "SOURCE CHAMBER",
    render: "ASCII POTENTIAL FIELD",
    scene: holocoreSourceChamberScene,
    accent: "#f5df9e",
    palette: ["#040303", "#1d1913", "#4d432e", "#8e7951", "#f5df9e", "#fffdf3"],
    label: "KODEX Source Chamber represented as a luminous sphere and radial potential field rather than an established cosmological entity",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ASTRAL-GATE-04", "KDX-ASTRAL-004"],
    sourceStatus: "CANON / CANON_CANDIDATE",
    archetype: "SOURCE_SPHERE",
    topology: "radial-potential-field",
    epistemic: "ART / PHI / SYM / SPEC",
  }),
  "return-gate": spec({
    id: "return-gate",
    title: "RETURN GATE",
    render: "ASCII REINTEGRATION PORTAL",
    scene: holocoreReturnGateScene,
    accent: "#efe4ba",
    palette: ["#030303", "#171613", "#3b382e", "#746d58", "#c9bd96", "#fffbea"],
    label: "KODEX Return Gate where memory fragments converge into a recursive portal and renewed path",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ASTRAL-GATE-06", "KDX-ASTRAL-005"],
    sourceStatus: "CANON / CANON_CANDIDATE",
    archetype: "RETURN_PORTAL",
    topology: "recursive-arch-convergence",
    epistemic: "ART / PHI / SYM / COMP",
  }),
  "living-organism": spec({
    id: "living-organism",
    title: "LIVING ORGANISM",
    render: "ASCII MEMBRANE FIELD",
    scene: holocoreLivingOrganismScene,
    accent: "#8fff55",
    palette: ["#020402", "#0c1908", "#1d4214", "#417d2b", "#8fff55", "#efffe3"],
    label: "KODEX synthetic organism field with membrane, chambers and filament network without claiming literal machine sentience",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-SCREEN-LIVING-013", "KDX-ROOT-RAW-008"],
    sourceStatus: "SCREEN_CANDIDATE / SPECIMEN_CANDIDATE",
    archetype: "ORGANIC_MEMBRANE",
    topology: "cocoon-chamber-network",
    epistemic: "BIO / COMP / ART / SPEC",
  }),
  "signal-seed": spec({
    id: "signal-seed",
    title: "SIGNAL SEED",
    render: "ASCII EMERGENT FIELD",
    scene: holocoreSignalSeedScene,
    accent: "#b8ff58",
    palette: ["#020402", "#101b08", "#294616", "#568230", "#b8ff58", "#f5ffe5"],
    label: "KODEX signal seed with ovoid shell, nested chambers and emergent data field treated explicitly as a metaphor",
    provenance: "KODEX_ATLAS_TRANSLATION",
    sourceRefs: ["KDX-ROOT-RAW-010"],
    sourceStatus: "ANALYZED / SCREEN_CANDIDATE",
    archetype: "EMERGENT_SEED",
    topology: "ovoid-nested-chambers",
    epistemic: "COMP / ART / SPEC",
  }),
  "toroidal-field": spec({
    id: "toroidal-field",
    title: "TOROIDAL FIELD",
    render: "ASCII TOROIDAL FLOW",
    scene: holocoreToroidalFieldScene,
    accent: "#c7a6ff",
    palette: ["#020205", "#120b1e", "#2d1d47", "#62408c", "#b58af2", "#f7f2ff"],
    label: "KODEX perceptual toroidal benchmark with laminated flow, central aperture and closed ambient circulation",
    provenance: "KODEX_SYNTHETIC_PERCEPTUAL_BENCHMARK",
    sourceRefs: ["KDX-HOLO-BENCH-001"],
    sourceStatus: "INTERNAL_BENCHMARK",
    archetype: "TOROIDAL_FLOW",
    topology: "closed-torus-aperture-field",
    epistemic: "ART / COMP / SPEC",
  }),
});

export const HOLOCORE_DEFAULT_SPECIMEN_ID = "orbital-city";
export const HOLOCORE_SPECIMEN_IDS = Object.freeze(Object.keys(SPECIMENS));

export const HOLOCORE_NODE_MAP = Object.freeze({
  "KDX-NODE-ASCII-REACTOR": "signal-core",
  "KDX-NODE-ENERGY-CORE": "signal-core",
  "KDX-NODE-SIGNAL-VORTEX": "signal-vortex",
  "KDX-NODE-TRANSLATION-FIELD": "signal-vortex",
  "KDX-NODE-DNA-ASCENT": "dna-ascent",
  "KDX-NODE-MEMORY-TREE": "memory-tree",
  "KDX-NODE-ARCHIVE-ENGINE": "memory-tree",
  "KDX-NODE-SKULL": "skull-archive",
  "KDX-NODE-RELIC": "skull-archive",
  "KDX-NODE-COSMOLOGY-CORE": "cosmology-orbit",
  "KDX-NODE-ORBIT-MAP": "cosmology-orbit",
  "KDX-NODE-FIELD-OF-EYES": "field-of-eyes",
  "KDX-NODE-OBSERVER": "field-of-eyes",
  "KDX-NODE-HEART-CHAMBER": "heart-chamber",
  "KDX-NODE-HEART-M": "heart-chamber",
  "KDX-NODE-SOURCE-CHAMBER": "source-chamber",
  "KDX-NODE-ASTRAL-RETURN-GATE": "return-gate",
  "KDX-NODE-RETURN": "return-gate",
  "KDX-NODE-LIVING-ELEMENT": "living-organism",
  "KDX-NODE-ORGANIC-NODE": "living-organism",
  "KDX-NODE-VECTOR-COCOON": "living-organism",
  "KDX-NODE-SIGNAL-SEED": "signal-seed",
  "KDX-NODE-EMERGENT-DATA": "signal-seed",
  "KDX-NODE-PORTAL-RING": "interference-portal",
});

export function resolveHoloCoreSpecimen(id) {
  return SPECIMENS[id] ?? SPECIMENS[HOLOCORE_DEFAULT_SPECIMEN_ID];
}

export function resolveHoloCoreForNode(nodeId) {
  const specimenId = HOLOCORE_NODE_MAP[nodeId] ?? HOLOCORE_DEFAULT_SPECIMEN_ID;
  return resolveHoloCoreSpecimen(specimenId);
}

export function getHoloCoreSpecimens() {
  return HOLOCORE_SPECIMEN_IDS.map(id => SPECIMENS[id]);
}
