import { mountKodexCrt, CRT_PRESETS } from '../dist/kodex-crt.esm.js';
const source=document.querySelector('#source'),stage=document.querySelector('#stage'),ctx=source.getContext('2d');
const preset=document.querySelector('#preset'),quality=document.querySelector('#quality'),readout=document.querySelector('.readout');
Object.keys(CRT_PRESETS).forEach(name=>{const o=document.createElement('option');o.value=o.textContent=name;preset.appendChild(o)});preset.value='observe';quality.value='balanced';
function resize(){const r=stage.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);source.width=Math.max(2,Math.round(r.width*d));source.height=Math.max(2,Math.round(r.height*d));}new ResizeObserver(resize).observe(stage);resize();
let pointer={x:.5,y:.5};stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width;pointer.y=(e.clientY-r.top)/r.height});
const crt=mountKodexCrt({source,container:stage,preset:'observe',quality:'balanced'});
function draw(t){const w=source.width,h=source.height,tt=t*.001;ctx.fillStyle='#030306';ctx.fillRect(0,0,w,h);const cx=w*(.5+(pointer.x-.5)*.08),cy=h*(.5+(pointer.y-.5)*.08);const g=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.min(w,h)*.38);g.addColorStop(0,'rgba(192,125,255,.72)');g.addColorStop(.28,'rgba(85,230,255,.18)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(cx,cy);for(let i=0;i<5;i++){ctx.rotate((i%2?1:-1)*.0015*t);ctx.strokeStyle=i===0?'rgba(235,225,255,.9)':'rgba(149,101,255,.48)';ctx.lineWidth=Math.max(1,w/1100);ctx.beginPath();ctx.ellipse(0,0,w*(.16+i*.035),h*(.08+i*.018),i*.22,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#f2f0ff';ctx.beginPath();ctx.arc(0,0,28+12*Math.sin(tt*1.7),0,Math.PI*2);ctx.fill();ctx.restore();ctx.strokeStyle='rgba(80,220,255,.42)';ctx.beginPath();for(let x=0;x<w;x+=4){const y=h*.72+Math.sin(x*.018+tt*3.5)*h*.03+Math.sin(x*.004-tt)*h*.015;x===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.fillStyle='rgba(255,255,255,.65)';ctx.font=`${Math.max(11,w/95)}px ui-monospace`;ctx.fillText('KDX://OBSERVE — THE ARCHIVE WATCHES',w*.04,h*.08);requestAnimationFrame(draw)}requestAnimationFrame(draw);
preset.addEventListener('change',()=>crt.setPreset(preset.value));quality.addEventListener('change',()=>crt.setQuality(quality.value));document.querySelectorAll('[data-anomaly]').forEach(btn=>btn.addEventListener('click',()=>crt.triggerAnomaly(btn.dataset.anomaly,1,520)));setInterval(()=>{const m=window.__KODEX_CRT_METRICS__;if(m)readout.textContent=`${m.fps} FPS · ${m.averageFrameTime} ms · ${m.profile}`},500);
