export const KDX_NATURAL_LAW_REGISTRY_PROFILE = Object.freeze({
  version: 'natural-law-patterns-v0.1.0',
  status: 'IMPLEMENTED_CANDIDATE',
  role: 'TRACE_ONLY_PATTERN_REGISTRY',
  createsParallelRuntime: false,
  mutatesAssemblyOS: false,
  mutatesDeepNavigation: false,
  mutatesMemory: false,
  claim: 'Natural patterns are source-scoped organizational models and design transduction candidates; shared form does not imply shared physical cause.',
});

const freezeArray = (values = []) => Object.freeze([...values]);
const freezeHints = (hints = {}) => Object.freeze(Object.fromEntries(
  Object.entries(hints).map(([key, values]) => [key, freezeArray(values)]),
));

const pattern = ({
  id,
  evidence_class,
  source_scope,
  mechanism_summary,
  formal_properties = [],
  compatible_geometry = [],
  compatible_operators = [],
  layer_hints = {},
  provenance_refs = [],
  prohibited_inferences = [],
}) => Object.freeze({
  id,
  evidence_class,
  source_scope,
  mechanism_summary,
  formal_properties: freezeArray(formal_properties),
  compatible_geometry: freezeArray(compatible_geometry),
  compatible_operators: freezeArray(compatible_operators),
  layer_hints: freezeHints(layer_hints),
  provenance_refs: freezeArray(provenance_refs),
  prohibited_inferences: freezeArray(prohibited_inferences),
});

export const KDX_NATURAL_LAW_EVIDENCE_CLASSES = Object.freeze([
  'FORMAL_MATHEMATICAL',
  'EMPIRICAL_BIOLOGICAL',
  'EMPIRICAL_PHYSICAL',
  'COMPUTATIONAL_MODEL',
  'METHODOLOGICAL_ANALOGY',
]);

export const KDX_NATURAL_LAW_PATTERNS = Object.freeze([
  pattern({
    id: 'TURING_REACTION_DIFFUSION',
    evidence_class: 'COMPUTATIONAL_MODEL',
    source_scope: 'Reaction–diffusion morphogenesis; applicability is system-specific.',
    mechanism_summary: 'Local reaction and differential diffusion can destabilize a homogeneous state and produce spatial pattern.',
    formal_properties: ['LOCAL_RULES', 'DIFFUSION', 'INSTABILITY', 'PATTERN_EMERGENCE'],
    compatible_geometry: ['LATTICE_FIELD', 'NODAL_PATTERN', 'SYMMETRY_BREAK'],
    compatible_operators: ['MANIFEST', 'REVEAL', 'MUTATE', 'RELATE'],
    layer_hints: {
      information_architecture: ['FIELD_DIFFERENTIATION'],
      layout: ['EMERGENT_REGION_MASKS'],
      responsive: ['PRESERVE_PATTERN_PHASE'],
      motion: ['DIFFUSE', 'REACT', 'DIFFERENTIATE'],
      sound: ['PHASE_COUPLED_MODULATION'],
      navigation: [],
      memory: ['RESIDUAL_FIELD'],
      return: ['PATTERN_AFTERIMAGE'],
    },
    provenance_refs: ['doi:10.1098/rstb.1952.0012'],
    prohibited_inferences: ['ALL_NATURAL_PATTERNS_ARE_TURING_PATTERNS', 'REACTION_DIFFUSION_PROVES_SACRED_GEOMETRY'],
  }),
  pattern({
    id: 'PHYLLOTAXIS_SPACING',
    evidence_class: 'EMPIRICAL_BIOLOGICAL',
    source_scope: 'Specific plant phyllotaxis and auxin-mediated organ placement; not universal biological growth.',
    mechanism_summary: 'Local spacing and auxin-transport relations can generate reiterative organ placement, including golden-angle/Fibonacci-like arrangements in many cases.',
    formal_properties: ['RADIAL_DISTRIBUTION', 'LOCAL_EXCLUSION', 'ITERATIVE_PLACEMENT', 'DENSITY_CONTROL'],
    compatible_geometry: ['CIRCLE_SPHERE', 'SPIRAL_HELIX', 'TESSELLATION_PACKING'],
    compatible_operators: ['MANIFEST', 'RELATE', 'CONVERGE', 'INHERIT'],
    layer_hints: {
      information_architecture: ['RADIAL_CLUSTER_DISTRIBUTION'],
      layout: ['GOLDEN_ANGLE_OPTION', 'NON_OVERLAPPING_RADIAL_PLACEMENT'],
      responsive: ['RADIUS_DENSITY_REBALANCE'],
      motion: ['ITERATIVE_EMERGENCE'],
      sound: ['ITERATIVE_SUBDIVISION'],
      navigation: [],
      memory: ['ORDERED_ACCUMULATION'],
      return: ['SPIRAL_SUMMARY_OPTION'],
    },
    provenance_refs: ['doi:10.1038/nature02081', 'doi:10.1073/pnas.0510457103'],
    prohibited_inferences: ['PHI_GOVERNS_ALL_LIFE', 'GOLDEN_RATIO_GUARANTEES_BEAUTY'],
  }),
  pattern({
    id: 'STOCHASTIC_BRANCHING',
    evidence_class: 'EMPIRICAL_BIOLOGICAL',
    source_scope: 'Drosophila dendritic arbor growth model; not a universal neural or cosmic law.',
    mechanism_summary: 'Simple stochastic branching, elongation, shrinkage and pausing rules can reproduce several macroscopic arbor properties.',
    formal_properties: ['BRANCHING', 'LOCAL_STOCHASTICITY', 'SPACE_FILLING', 'ECONOMICAL_GROWTH'],
    compatible_geometry: ['BRANCH_TREE', 'SYMMETRY_BREAK'],
    compatible_operators: ['DIVERGE', 'MUTATE', 'INHERIT', 'RECONSTRUCT'],
    layer_hints: {
      information_architecture: ['LINEAGE_TREE', 'BRANCHING_TOPIC_FAMILY'],
      layout: ['BOUNDED_BRANCH_GROWTH'],
      responsive: ['BRANCH_ANGLE_COMPRESSION'],
      motion: ['GROW', 'RETRACT', 'PAUSE', 'REBRANCH'],
      sound: ['MOTIF_DESCENDANTS'],
      navigation: ['BRANCH_AFFINITY_HINT_ONLY'],
      memory: ['LINEAGE_TRACE'],
      return: ['BRANCH_SIGNATURE'],
    },
    provenance_refs: ['doi:10.1038/s41467-025-60800-7'],
    prohibited_inferences: ['NEURONS_EQUAL_GALAXIES', 'STOCHASTIC_BRANCHING_EXPLAINS_ALL_NETWORKS'],
  }),
  pattern({
    id: 'ADAPTIVE_TRANSPORT_NETWORK',
    evidence_class: 'EMPIRICAL_BIOLOGICAL',
    source_scope: 'Physarum transport networks and their mathematical abstraction; design analogy only outside that domain.',
    mechanism_summary: 'Local flow feedback can strengthen useful paths and weaken costly paths, balancing efficiency, cost and fault tolerance without a central planner.',
    formal_properties: ['NETWORK', 'FLOW_FEEDBACK', 'PATH_REINFORCEMENT', 'COST_EFFICIENCY_TRADEOFF'],
    compatible_geometry: ['LATTICE_FIELD', 'BRANCH_TREE', 'TESSELLATION_PACKING'],
    compatible_operators: ['RELATE', 'CONVERGE', 'INHERIT', 'RECONSTRUCT'],
    layer_hints: {
      information_architecture: ['ADAPTIVE_CONNECTION_EMPHASIS'],
      layout: ['NETWORK_PATH_WEIGHT'],
      responsive: ['PRESERVE_HIGH_VALUE_CONNECTIONS'],
      motion: ['FLOW_REINFORCEMENT'],
      sound: ['PATH_DENSITY_MODULATION'],
      navigation: ['SHARED_PATTERN_AFFINITY_HINT_ONLY'],
      memory: ['CONNECTION_RESIDUE'],
      return: ['NETWORK_SIGNATURE'],
    },
    provenance_refs: ['doi:10.1126/science.1177894'],
    prohibited_inferences: ['AUTO_NAVIGATE_USER', 'ENGAGEMENT_OPTIMIZATION', 'PHYSARUM_IS_A_MODEL_OF_HUMAN_DESIRE'],
  }),
  pattern({
    id: 'VORONOI_DELAUNAY',
    evidence_class: 'FORMAL_MATHEMATICAL',
    source_scope: 'Computational geometry; biological use is model- and tissue-specific.',
    mechanism_summary: 'Voronoi partitions space by nearest seed; the Delaunay dual connects neighboring seeds.',
    formal_properties: ['NEIGHBORHOOD', 'PARTITION', 'PROXIMITY', 'DUAL_GRAPH'],
    compatible_geometry: ['TESSELLATION_PACKING', 'LATTICE_FIELD'],
    compatible_operators: ['RELATE', 'CONVERGE', 'REVEAL', 'INHERIT'],
    layer_hints: {
      information_architecture: ['SEMANTIC_TERRITORIES', 'LOCAL_NEIGHBORHOODS'],
      layout: ['VORONOI_PARTITION', 'DELAUNAY_ADJACENCY'],
      responsive: ['RECOMPUTE_TERRITORY_PRESERVE_FOCUS'],
      motion: ['CELL_BOUNDARY_RELAXATION'],
      sound: ['NEIGHBOR_COUPLING'],
      navigation: ['NEIGHBOR_AFFINITY_HINT_ONLY'],
      memory: ['VISITED_TERRITORY_TRACE'],
      return: ['TERRITORY_SIGNATURE'],
    },
    provenance_refs: ['doi:10.1038/s41467-018-05376-1'],
    prohibited_inferences: ['PROXIMITY_EQUALS_CAUSATION', 'VORONOI_IS_A_UNIVERSAL_NATURAL_LAW'],
  }),
  pattern({
    id: 'COUPLED_OSCILLATORS',
    evidence_class: 'FORMAL_MATHEMATICAL',
    source_scope: 'Coupled-oscillator synchronization models; KODEX use is a timing/scheduling abstraction.',
    mechanism_summary: 'Interacting oscillators can transition between incoherent and phase-coherent regimes depending on coupling and network structure.',
    formal_properties: ['PHASE', 'COUPLING', 'SYNCHRONIZATION', 'PERIODICITY'],
    compatible_geometry: ['CIRCLE_SPHERE', 'NODAL_PATTERN', 'LATTICE_FIELD', 'AXIS'],
    compatible_operators: ['RELATE', 'CONVERGE', 'OBSERVE', 'RETURN'],
    layer_hints: {
      information_architecture: [],
      layout: [],
      responsive: [],
      motion: ['SHARED_PHASE_BUS', 'PHASE_OFFSETS'],
      sound: ['MASTER_PHASE', 'SUBDIVISION', 'POLYRHYTHM'],
      navigation: [],
      memory: ['PHASE_RESIDUE_OPTION'],
      return: ['SLOW_CONVERGENCE'],
    },
    provenance_refs: ['doi:10.1103/PhysRevE.71.036151'],
    prohibited_inferences: ['BIOMETRIC_HEART_READING', 'EMOTIONAL_STATE_INFERENCE', 'HEALING_FREQUENCY_CLAIM'],
  }),
  pattern({
    id: 'SYMMETRY_BREAKING',
    evidence_class: 'METHODOLOGICAL_ANALOGY',
    source_scope: 'Formal/physical concept applied in KODEX as a controlled transition metaphor.',
    mechanism_summary: 'A symmetric or equivalent state differentiates into non-equivalent states under a transition or perturbation.',
    formal_properties: ['SYMMETRY', 'PERTURBATION', 'DIFFERENTIATION', 'STATE_CHANGE'],
    compatible_geometry: ['SYMMETRY_BREAK', 'AXIS', 'CIRCLE_SPHERE'],
    compatible_operators: ['MUTATE', 'DIVERGE', 'INHERIT', 'MANIFEST'],
    layer_hints: {
      information_architecture: ['DIFFERENTIATION'],
      layout: ['CONTROLLED_ASYMMETRY'],
      responsive: ['PRESERVE_HIERARCHY_AFTER_BREAK'],
      motion: ['PERTURB', 'SPLIT'],
      sound: ['SYMMETRY_TO_VARIATION'],
      navigation: ['BRANCH_STATE_HINT_ONLY'],
      memory: ['DIFFERENTIATION_TRACE'],
      return: ['ASYMMETRY_RESIDUE'],
    },
    provenance_refs: ['kodex:geometric-transduction:SYMMETRY_BREAK'],
    prohibited_inferences: ['ALL_DIFFERENTIATION_HAS_ONE_PHYSICAL_CAUSE'],
  }),
  pattern({
    id: 'NESTED_RECURSION',
    evidence_class: 'FORMAL_MATHEMATICAL',
    source_scope: 'Recursive computation and finite nested representations; natural self-similarity claims remain source-specific.',
    mechanism_summary: 'A transformation reuses a rule on a descendant state, producing nested structure while computation remains finitely bounded.',
    formal_properties: ['RECURSION', 'NESTING', 'SCALE_TRANSITION', 'FINITE_ACTIVE_WINDOW'],
    compatible_geometry: ['NESTED_SCALE', 'SPIRAL_HELIX', 'BRANCH_TREE'],
    compatible_operators: ['APPROACH', 'CROSS', 'INHERIT', 'RETURN', 'RECONSTRUCT'],
    layer_hints: {
      information_architecture: ['NESTED_REPRESENTATIONS'],
      layout: ['FINITE_RECURSIVE_WINDOW'],
      responsive: ['REDUCE_SIMULTANEOUS_DEPTH'],
      motion: ['INWARD_SCALE_TRANSITION'],
      sound: ['NESTED_TIME_SCALE'],
      navigation: ['DEPTH_CONTINUITY_HINT_ONLY'],
      memory: ['DEPTH_TRACE'],
      return: ['SPIRAL_HELIX_SIGNATURE'],
    },
    provenance_refs: ['kodex:deep-navigation', 'kodex:infinite-descent'],
    prohibited_inferences: ['NATURE_IS_INFINITELY_SELF_SIMILAR_AT_ALL_SCALES'],
  }),
  pattern({
    id: 'DEEP_REPRESENTATION_COMPRESSION',
    evidence_class: 'METHODOLOGICAL_ANALOGY',
    source_scope: 'KODEX anti-complexity principle inspired by positive-geometry methods; not an implementation of amplituhedron mathematics.',
    mechanism_summary: 'When many local exceptions accumulate, search for a lower-dimensional relational representation from which the desired behavior follows as a constraint.',
    formal_properties: ['REPRESENTATION_CHANGE', 'CONSTRAINT_COMPRESSION', 'EMERGENT_BEHAVIOR', 'ANTI_SPECIAL_CASE'],
    compatible_geometry: ['NESTED_SCALE', 'POINT_CENTER', 'AXIS', 'LATTICE_FIELD'],
    compatible_operators: ['OBSERVE', 'REVEAL', 'RECONSTRUCT', 'RETURN', 'RELATE'],
    layer_hints: {
      information_architecture: ['PATTERN_SIGNATURES_OVER_MANUAL_TAG_EXPLOSION'],
      layout: ['RULES_OVER_LOCAL_PATCHES'],
      responsive: ['STRUCTURE_PRESERVING_TRANSFORMATION'],
      motion: ['SHARED_LAW_OVER_PER_ELEMENT_TIMING'],
      sound: ['SHARED_PHASE_OVER_PER_CLIP_TIMING'],
      navigation: ['STATE_SPACE_HINT_ONLY'],
      memory: ['COMPRESS_ROUTE_TO_SIGNATURE'],
      return: ['GEOMETRIC_MEMORY_SIGNATURE'],
    },
    provenance_refs: ['arxiv:1312.2007'],
    prohibited_inferences: ['KODEX_IMPLEMENTS_AMPLITUHEDRON', 'AMPLITUHEDRON_PROVES_UNIVERSAL_SACRED_GEOMETRY'],
  }),
]);

export const KDX_NATURAL_LAW_PATTERN_BY_ID = Object.freeze(Object.fromEntries(
  KDX_NATURAL_LAW_PATTERNS.map((entry) => [entry.id, entry]),
));

export function getNaturalLawPattern(id) {
  return KDX_NATURAL_LAW_PATTERN_BY_ID[id] || null;
}
