export const KDX_SEMANTIC_IR_FIXTURES = Object.freeze([
  Object.freeze({
    id: 'KDX-SEM-IMPERMANENCE',
    version: '0.1.1',
    status: 'NEEDS_CONFIRMATION',
    question: 'WHAT PERSISTS WHEN FORM CHANGES?',
    principles: Object.freeze(['IMPERMANENCE', 'CONTINUITY']),
    epistemic: Object.freeze(['NEEDS_CONFIRMATION']),
    operators: Object.freeze(['MANIFEST', 'MUTATE', 'ERODE', 'INHERIT']),
    depth_types: Object.freeze(['LINEAGE', 'INFORMATION']),
    geometry: Object.freeze({
      primitives: Object.freeze(['SYMMETRY_BREAK', 'SPIRAL_HELIX']),
      relation: 'ORDER BREAKS, TRACE PERSISTS, RETURN RE-ENTERS WITH DIFFERENCE',
      evidence_class: 'KODEX_SYMBOLIC',
      notes: 'Spiral/helix is used as recurrence-with-transformation; no universal sacred-geometry claim is implied.',
    }),
    scene_state: 'ARCHIVE',
    plate_type: 'KNOWLEDGE_PLATE',
    observer_lens: 'MICROSCOPE',
    seed: 'semantic-ir-impermanence-v0',
    manifestation: Object.freeze({
      title: 'IMPERMANENCE',
      macro_signal: 'FORM CHANGES. A TRACE REMAINS.',
      payload_type: 'CONCEPT',
      payload_ref: 'KDX-SEM-IMPERMANENCE',
      status: 'NEEDS_CONFIRMATION',
      allow_motion: true,
    }),
    interaction: Object.freeze({ action: 'REVEAL_RESIDUE', selection_required: true }),
    memory: Object.freeze({ effect: 'RESIDUE', retains: Object.freeze(['prior-form-trace']) }),
    return: Object.freeze({ effect: 'RETURNED_FORM' }),
    provenance_refs: Object.freeze(['repo:src/lib/kodex/grammar/semantic-ir-fixtures.v0.1.js#KDX-SEM-IMPERMANENCE']),
  }),
  Object.freeze({
    id: 'KDX-SEM-INTERDEPENDENCE',
    version: '0.1.1',
    status: 'NEEDS_CONFIRMATION',
    question: 'WHAT EXISTS BETWEEN TWO THINGS?',
    principles: Object.freeze(['INTERDEPENDENCE', 'RELATION']),
    epistemic: Object.freeze(['NEEDS_CONFIRMATION']),
    operators: Object.freeze(['REVEAL', 'RELATE', 'DIVERGE', 'CONVERGE']),
    depth_types: Object.freeze(['SYSTEMIC', 'EPISTEMIC']),
    geometry: Object.freeze({
      primitives: Object.freeze(['LATTICE_FIELD', 'NESTED_SCALE']),
      relation: 'LOCAL RELATIONS FORM A DISTRIBUTED FIELD; SCALE REVEALS NEW NEIGHBORHOODS',
      evidence_class: 'KODEX_SYMBOLIC',
      notes: 'The mapping uses adjacency and scale as formal relations; it does not claim exact self-similarity across all natural systems.',
    }),
    scene_state: 'MACHINE',
    plate_type: 'JUNCTION_PLATE',
    observer_lens: 'SYSTEM',
    seed: 'semantic-ir-interdependence-v0',
    manifestation: Object.freeze({
      title: 'INTERDEPENDENCE',
      macro_signal: 'RELATION IS PART OF THE FORM.',
      payload_type: 'MAP',
      payload_ref: 'KDX-SEM-INTERDEPENDENCE',
      status: 'NEEDS_CONFIRMATION',
      allow_motion: true,
    }),
    route_slate: Object.freeze([
      Object.freeze({ target_node: 'KDX-SEM-IMPERMANENCE', role: 'BRIDGE' }),
      Object.freeze({ target_node: 'KDX-SEM-OBSERVER', role: 'CONTINUITY' }),
      Object.freeze({ target_node: 'KDX-SEM-INTERDEPENDENCE-RETURN', role: 'RETURN' }),
    ]),
    interaction: Object.freeze({ action: 'TRACE_RELATION', selection_required: true }),
    memory: Object.freeze({ effect: 'ROUTE_SIGNATURE', retains: Object.freeze(['chosen-relation']) }),
    return: Object.freeze({ effect: 'THRESHOLD_PRIME' }),
    provenance_refs: Object.freeze(['repo:src/lib/kodex/grammar/semantic-ir-fixtures.v0.1.js#KDX-SEM-INTERDEPENDENCE']),
  }),
  Object.freeze({
    id: 'KDX-SEM-OBSERVER',
    version: '0.1.1',
    status: 'NEEDS_CONFIRMATION',
    question: 'WHAT CHANGES WHEN OBSERVATION LEAVES A TRACE?',
    principles: Object.freeze(['OBSERVER', 'PARTICIPATION']),
    epistemic: Object.freeze(['NEEDS_CONFIRMATION']),
    operators: Object.freeze(['OBSERVE', 'REVEAL', 'INHERIT', 'RETURN']),
    depth_types: Object.freeze(['EPISTEMIC', 'META']),
    geometry: Object.freeze({
      primitives: Object.freeze(['POINT_CENTER', 'AXIS']),
      relation: 'AN OBSERVATION HAS A POSITION, ORIENTATION AND TRACEABLE FRAME',
      evidence_class: 'KODEX_SYMBOLIC',
      notes: 'Observer geometry encodes viewpoint and framing only; it is not a quantum-consciousness claim.',
    }),
    scene_state: 'COSMOLOGY',
    plate_type: 'ACTIVATOR_PLATE',
    observer_lens: 'META',
    seed: 'semantic-ir-observer-v0',
    manifestation: Object.freeze({
      title: 'OBSERVER',
      macro_signal: 'OBSERVATION CREATES A TRACE IN THE JOURNEY.',
      payload_type: 'FIELD',
      payload_ref: 'KDX-SEM-OBSERVER-FIELD',
      status: 'NEEDS_CONFIRMATION',
      activation_id: 'MOTION_03_FIELD_MARBLE',
      explicit_action_required: true,
      allow_motion: true,
    }),
    interaction: Object.freeze({ action: 'OBSERVE_FIELD', selection_required: true }),
    memory: Object.freeze({ effect: 'TRACE', retains: Object.freeze(['observation-event']) }),
    return: Object.freeze({ effect: 'TRACE_VISIBLE' }),
    provenance_refs: Object.freeze(['repo:src/lib/kodex/grammar/semantic-ir-fixtures.v0.1.js#KDX-SEM-OBSERVER']),
  }),
]);

export function getSemanticIrFixture(id) {
  return KDX_SEMANTIC_IR_FIXTURES.find((fixture) => fixture.id === id) || null;
}
