import type { NodeRecipe, SliceCoordinate } from "./types";

export const verticalSliceRecipes: Record<SliceCoordinate, NodeRecipe> = {
  A: {
    coordinate: "A",
    assignmentStatus: "CANONICAL",
    title: "THRESHOLD",
    question: "What are you willing to activate, and under which conditions?",
    worldIds: ["threshold-world"],
    actions: [
      {
        id: "ORIENT_SIGNAL",
        label: "Orient toward signal",
        description: "Begin through a visible signal and its attractor.",
      },
      {
        id: "OPEN_TRACE",
        label: "Open the first trace",
        description: "Begin through provenance, versions and memory.",
      },
      {
        id: "MAP_RELATION",
        label: "Map the first relation",
        description: "Begin through a relational or cosmological field.",
      },
    ],
    exits: [
      {
        target: "B",
        label: "Enter Signal Vortex",
        relationId: "A_TO_B_FIRST_SIGNAL",
        conditionId: "A_ORIENTATION_SIGNAL",
        consequence: "Signal becomes the first active relation.",
      },
      {
        target: "C",
        label: "Enter Archive Trace Field",
        relationId: "A_TO_C_FIRST_TRACE",
        conditionId: "A_ORIENTATION_TRACE",
        consequence: "The journey begins through evidence and memory.",
      },
      {
        target: "H",
        label: "Enter Cosmology Core",
        relationId: "A_TO_H_FIRST_RELATION",
        conditionId: "A_ORIENTATION_RELATION",
        consequence: "The journey begins through relational structure.",
      },
    ],
    organism: {
      family: "FIELD",
      presetId: "threshold-portal",
      implementationStatus: "PROTOTYPE",
      fallback: "/img/kodex/works/mandala-0cin-negativo.png",
    },
    presentationMode: "ORGANISM",
  },
  B: {
    coordinate: "B",
    assignmentStatus: "NEEDS_CREATOR_APPROVAL",
    title: "SIGNAL VORTEX",
    question: "When many signals converge, what remains distinguishable?",
    worldIds: ["machine-world", "cosmology-world"],
    actions: [
      {
        id: "OBSERVE_ATTRACTOR",
        label: "Observe the attractor",
        description: "Increase convergence and expose relational exits.",
      },
      {
        id: "ISOLATE_ECHO",
        label: "Isolate one echo",
        description: "Commit one signal that will return later as a delayed consequence.",
      },
    ],
    exits: [
      {
        target: "H",
        label: "Translate signal into orbit",
        relationId: "B_TO_H_SIGNAL_BECOMES_ORBIT",
        conditionId: "B_ATTRACTOR_OBSERVED",
        consequence: "A convergent signal becomes a relation among moving bodies.",
      },
      {
        target: "C",
        label: "Inspect the isolated echo",
        relationId: "B_TO_C_SIGNAL_BECOMES_TRACE",
        conditionId: "B_ECHO_ISOLATED",
        consequence: "The selected echo becomes an archive trace.",
      },
      {
        target: "M",
        label: "Enter M@SIGNAL",
        relationId: "B_TO_M_CONVERGENCE_RESONANCE",
        conditionId: "B_M_AVAILABLE",
        consequence: "The attractor opens an optional orientation portal.",
      },
      {
        target: "Y",
        label: "Converge at Return",
        relationId: "B_TO_Y_SIGNAL_RETURN",
        conditionId: "Y_ELIGIBLE",
        consequence: "Return records how signal selection shaped the route.",
      },
    ],
    organism: {
      family: "VORTEX",
      presetId: "signal-vortex",
      implementationStatus: "PROTOTYPE",
      fallback: "/img/kodex/organisms/signal-vortex-fallback.svg",
    },
    presentationMode: "ORGANISM",
  },
  C: {
    coordinate: "C",
    assignmentStatus: "NEEDS_CREATOR_APPROVAL",
    title: "ARCHIVE TRACE FIELD",
    question: "What changes when a trace is inspected instead of merely remembered?",
    worldIds: ["memory-world", "artifact-world"],
    actions: [
      {
        id: "OPEN_SOURCE",
        label: "Open source record",
        description: "Add provenance and unresolved uncertainty to the route.",
      },
      {
        id: "TRACE_ARCHIVE_RELATION",
        label: "Trace a relation",
        description: "Connect two records and create a growth seed.",
      },
    ],
    exits: [
      {
        target: "K",
        label: "Germinate the traced relation",
        relationId: "C_TO_K_ARCHIVE_GERMINATES",
        conditionId: "C_RELATION_TRACED",
        consequence: "A verified relation becomes a seed for visible growth.",
      },
      {
        target: "B",
        label: "Release trace as signal",
        relationId: "C_TO_B_TRACE_RETURNS_AS_SIGNAL",
        conditionId: "C_TO_B_AVAILABLE",
        consequence: "The trace re-enters B and may produce B′.",
      },
      {
        target: "M",
        label: "Enter M@MEMORY",
        relationId: "C_TO_M_MEMORY_RESONANCE",
        conditionId: "C_M_AVAILABLE",
        consequence: "Provenance and relation open an optional Heart approach.",
      },
      {
        target: "Y",
        label: "Converge at Return",
        relationId: "C_TO_Y_ARCHIVE_RETURN",
        conditionId: "Y_ELIGIBLE",
        consequence: "Return includes opened sources and unresolved provenance.",
      },
    ],
    organism: {
      family: "FIELD",
      presetId: "archive-trace-field",
      implementationStatus: "PLANNED",
      fallback: "/img/kodex/organisms/archive-trace-field-fallback.svg",
    },
    presentationMode: "ORGANISM",
  },
  H: {
    coordinate: "H",
    assignmentStatus: "NEEDS_CREATOR_APPROVAL",
    title: "COSMOLOGY CORE",
    question: "Which relation becomes visible when the center is no longer fixed?",
    worldIds: ["cosmology-world", "machine-world"],
    actions: [
      {
        id: "SELECT_ORBIT",
        label: "Select an orbital relation",
        description: "Commit one relation and alter the next field.",
      },
      {
        id: "DESTABILIZE_CENTER",
        label: "Displace the center",
        description: "Change phase relationships and arm a mutated signal revisit.",
      },
    ],
    exits: [
      {
        target: "K",
        label: "Translate orbit into growth",
        relationId: "H_TO_K_ORBIT_BECOMES_GROWTH",
        conditionId: "H_ORBIT_SELECTED",
        consequence: "A selected relation becomes a growth condition.",
      },
      {
        target: "B",
        label: "Collapse orbit into signal",
        relationId: "H_TO_B_ORBIT_BECOMES_SIGNAL",
        conditionId: "H_CENTER_DISPLACED",
        consequence: "The displaced center returns as a changed attractor.",
      },
      {
        target: "M",
        label: "Enter M@COSMOLOGY",
        relationId: "H_TO_M_COSMOLOGY_RESONANCE",
        conditionId: "H_M_AVAILABLE",
        consequence: "Multiple relations open an optional Heart approach.",
      },
      {
        target: "Y",
        label: "Converge at Return",
        relationId: "H_TO_Y_RELATIONAL_RETURN",
        conditionId: "Y_ELIGIBLE",
        consequence: "Return includes selected relations and displaced centers.",
      },
    ],
    organism: {
      family: "ORBITAL",
      presetId: "cosmology-core",
      implementationStatus: "PLANNED",
      fallback: "/img/kodex/organisms/cosmology-core-fallback.svg",
    },
    presentationMode: "ORGANISM",
  },
  K: {
    coordinate: "K",
    assignmentStatus: "NEEDS_CREATOR_APPROVAL",
    title: "ARCHIVE TREE",
    question: "What must be rooted before a form can remember?",
    worldIds: ["memory-world", "artifact-world", "cosmology-world"],
    actions: [
      {
        id: "PLANT_SEED",
        label: "Plant the archive seed",
        description: "Start deterministic staged growth from a prior relation.",
      },
      {
        id: "ADVANCE_GROWTH",
        label: "Advance one growth stage",
        description: "Move from seed toward root, trunk, branches and crown.",
        repeatable: true,
      },
      {
        id: "SELECT_BRANCH",
        label: "Select one branch relation",
        description: "Commit one branch that may reappear in H or Y.",
      },
    ],
    exits: [
      {
        target: "C",
        label: "Return growth to provenance",
        relationId: "K_TO_C_GROWTH_RETURNS_TO_ARCHIVE",
        conditionId: "K_TO_C_AVAILABLE",
        consequence: "Growth requests a source relation before stabilization.",
      },
      {
        target: "H",
        label: "Translate branch into orbit",
        relationId: "K_TO_H_BRANCH_BECOMES_RELATION",
        conditionId: "K_BRANCH_SELECTED",
        consequence: "A branch becomes an orbital relation.",
      },
      {
        target: "M",
        label: "Enter M@GROWTH",
        relationId: "K_TO_M_GROWTH_RESONANCE",
        conditionId: "K_M_AVAILABLE",
        consequence: "A rooted structure opens an optional Heart manifestation.",
      },
      {
        target: "Y",
        label: "Converge at Return",
        relationId: "K_TO_Y_GROWTH_RETURN",
        conditionId: "K_Y_ELIGIBLE",
        consequence: "Return receives the actual growth stage.",
      },
    ],
    organism: {
      family: "GROWTH",
      presetId: "archive-tree",
      implementationStatus: "PLANNED",
      fallback: "/img/kodex/organisms/archive-tree-fallback.svg",
    },
    presentationMode: "ORGANISM",
  },
  M: {
    coordinate: "M",
    assignmentStatus: "CANONICAL",
    title: "HEART / 0",
    question: "What relation becomes coherent when the route pauses without being ranked?",
    worldIds: ["memory-world", "machine-world", "cosmology-world", "artifact-world"],
    actions: [
      {
        id: "ACKNOWLEDGE_RELATION",
        label: "Acknowledge the active relation",
        description: "Record a voluntary orientation without identity or emotion inference.",
      },
      {
        id: "RETURN_TO_ANCHOR",
        label: "Return to the prior coordinate",
        description: "Restore the exact route anchor and expose its mutated state.",
      },
    ],
    exits: [],
    organism: null,
    presentationMode: "CONTEXTUAL_HEART",
  },
  Y: {
    coordinate: "Y",
    assignmentStatus: "CANONICAL",
    title: "RETURN / +∞",
    question: "What did this route make visible, and what remains unresolved?",
    worldIds: ["return-world", "memory-world", "artifact-world"],
    actions: [
      {
        id: "GENERATE_RETURN",
        label: "Generate the Return",
        description: "Produce a deterministic artifact from the current event trace.",
      },
      {
        id: "BEGIN_NEW_CYCLE",
        label: "Begin a transformed cycle",
        description: "Return to A while preserving the completed artifact separately.",
      },
    ],
    exits: [
      {
        target: "A",
        label: "Begin a transformed cycle",
        relationId: "Y_TO_A_REENTRY",
        conditionId: "Y_RETURN_GENERATED",
        consequence: "Creates a new session seed and preserves the prior artifact.",
      },
      {
        target: "C",
        label: "Re-enter an unresolved source",
        relationId: "Y_TO_C_UNRESOLVED_SOURCE",
        conditionId: "Y_REENTER_C_AVAILABLE",
        consequence: "Re-enters C′ without fabricating a prior journey.",
      },
      {
        target: "H",
        label: "Re-enter an unresolved relation",
        relationId: "Y_TO_H_UNRESOLVED_RELATION",
        conditionId: "Y_REENTER_H_AVAILABLE",
        consequence: "Re-enters H′ at a previously unresolved phase.",
      },
      {
        target: "K",
        label: "Re-enter unfinished growth",
        relationId: "Y_TO_K_UNFINISHED_GROWTH",
        conditionId: "Y_REENTER_K_AVAILABLE",
        consequence: "Re-enters K′ at the exact stored growth stage.",
      },
    ],
    organism: null,
    presentationMode: "TRACE_COMPOSITE",
  },
};

export const verticalSliceCoordinates = Object.keys(verticalSliceRecipes) as SliceCoordinate[];
