import json
import os
import sys

def assemble_astro_plate(manifest_path, output_astro_path):
    if not os.path.exists(manifest_path):
        raise FileNotFoundError(f"Manifest path not found: {manifest_path}")

    with open(manifest_path, 'r', encoding='utf8') as f:
        manifest = json.load(f)

    spec_id = manifest["spec_id"]
    plate_type = manifest["plate_type"]
    recipe_id = manifest["recipe_id"]
    checksum = manifest["deterministic_checksum"]
    slots = manifest["slots"]

    # Component imports mapping
    import_statements = [
        '---',
        '// Generated by Assembly OS L8 — Plate Assembler',
        f'// Specimen: {spec_id} | Recipe: {recipe_id} | Checksum: {checksum}',
        'import KodexObserveV2Scene from "../scenes/KodexObserveV2Scene.astro";',
        'import KodexThresholdPortalScene from "../scenes/KodexThresholdPortalScene.astro";',
        'import KodexField from "../field/KodexField.astro";',
        'import KodexCrtLayer from "../crt/KodexCrtLayer.astro";',
        'import KodexEje from "../eje/KodexEje.astro";',
        'import KodexAscii from "../ascii/KodexAscii.astro";',
        'import KodexArtifact from "../artifact/KodexArtifact.astro";',
        '',
        'interface Props {',
        '  class?: string;',
        '}',
        '',
        'const { class: className = "" } = Astro.props;',
        '---'
    ]

    markup = [
        f'<!-- KODEX L8 COMPILED PLATE | Specimen: {spec_id} | Checksum: {checksum} -->',
        f'<section class={{`kdx-plate-compiled kdx-plate-compiled--{plate_type.lower()} ${{className}}`.trim()}} data-assembly-layer="L8" data-checksum="{checksum}" data-spec-id="{spec_id}">',
        '  <div class="kdx-plate-compiled__container">'
    ]

    for slot in slots:
        slot_id = slot["slot_id"]
        role = slot["slot_role"]
        elem_id = slot["assigned_element_id"]
        fallback = slot["fallback"]
        accessibility = slot["accessibility_contract"]

        markup.append(f'    <!-- Slot: {slot_id} ({role}) -> Element: {elem_id} -->')
        markup.append(f'    <div class="kdx-plate-compiled__slot" data-slot-id="{slot_id}" data-slot-role="{role}">')
        
        if elem_id == "holocore-observe-v2":
            markup.append('      <KodexObserveV2Scene />')
        elif elem_id == "holocore-threshold-portal":
            markup.append('      <KodexThresholdPortalScene />')
        elif elem_id == "holocore-field":
            markup.append('      <KodexField />')
        elif elem_id == "holocore-crt-layer":
            markup.append('      <KodexCrtLayer preset="observe" />')
        elif elem_id == "holocore-eje-axis":
            markup.append('      <KodexEje posicion={0} />')
        elif elem_id == "holocore-ascii":
            markup.append('      <KodexAscii glyphs="kodex" label="Kodex Assembly Symbol" />')
        else:
            markup.append(f'      <KodexArtifact />')
            
        markup.append(f'      <template data-fallback="{fallback}"></template>')
        markup.append('    </div>')

    markup.append('  </div>')
    markup.append('</section>')

    full_astro_code = "\n".join(import_statements + [''] + markup)

    os.makedirs(os.path.dirname(output_astro_path), exist_ok=True)
    with open(output_astro_path, 'w', encoding='utf8') as f:
        f.write(full_astro_code)

    return full_astro_code

def main():
    manifest_path = '/Users/user1/wenu-frontend/ops/factory/recipe-engine/sample_compiled_manifest.json'
    out_astro_path = '/Users/user1/wenu-frontend/src/components/kodex/compiled/KodexPlateCompiled.astro'
    
    code = assemble_astro_plate(manifest_path, out_astro_path)
    print(f"✅ Successfully compiled L8 Astro component to: {out_astro_path}")
    print(f"Generated Code Size: {len(code.splitlines())} lines")

if __name__ == '__main__':
    main()
